import turtle

print(turtle.pos())
turtle.Pen()
turtle.forward(90)
turtle.pencolor("red")
turtle.right(57)
turtle.Pen()
turtle.forward(90)
turtle.pencolor("red")
turtle.right(57)
turtle.Pen()
turtle.forward(90)
turtle.pencolor("red")
turtle.right(57)
turtle.Pen()
turtle.forward(90)
turtle.pencolor("red")
turtle.right(57)
turtle.Pen()
turtle.forward(90)
turtle.pencolor("red")
turtle.right(57)
turtle.Pen()
turtle.forward(90)
turtle.pencolor("red")
turtle.right(57)
turtle.Pen()
turtle.forward(90)
turtle.pencolor("red")
turtle.right(57)
# turtle.penup()
turtle.mainloop()