-- Truy xuất thông tin của Table Tham gia đề tài
-- Lấy ra Mã khoa và Tên khoa tương ứng
-- Lấy ra Mã GV, tên GV và họ tên người thân tương ứng
-- Lấy ra Mã GV, tên GV và tên khoa tương ứng mà giáo viên đó làm việc. (Gợi ý: Bộ môn nằm trong 
select * from BOMON;
select * from GIAOVIEN;
SELECT * FROM GIAOVIEN, BOMON;
SELECT GV.MAGV, GV.HOTEN, BM.TENBM FROM GIAOVIEN AS GV, BOMON AS BM;
-- TRUY VAN MA 
SELECT GV.MAGV, GV.HOTEN,GV.MABM AS MABOMON, BM.TENBM AS "TÊN BỘ MÔN" FROM GIAOVIEN AS GV, BOMON AS BM WHERE GV.MABM = BM.MABM;

SELECT * FROM DETAI;
SELECT KHOA.MAKHOA, KHOA.TENKHOA  FROM KHOA;

SELECT * FROM NGUOITHAN;

SELECT GV.MAGV, GV.HOTEN , NT.TEN AS "TÊN NGƯỜI THÂN " FROM GIAOVIEN AS GV, NGUOITHAN AS NT WHERE GV.MAGV = NT.MAGV ;

SELECT GV.MAGV, GV.HOTEN,GV.MABM AS MABOMON,KHOA.TENKHOA,BM.TENBM AS "TÊN BỘ MÔN" FROM GIAOVIEN AS
GV, BOMON AS BM, KHOA WHERE GV.MABM = BM.MABM AND BM.MAKHOA = KHOA.MAKHOA ;